[tool.poetry]
name = "pybricks-micropython"
version = "0.1.0"
description = "Development dependencies for pybricks-micropython"
authors = ["The Pybricks Authors <dev@pybricks.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^20.8b0"
pyusb = "^1.0.2"
PyGithub = "^1.51"
flake8 = "^3.8.3"
GitPython = "^3.1.11"
azure-cosmosdb-table = "^1.0.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
