name: Build

on:
  push:
    tags-ignore:
      '@pybricks/**'
  pull_request:

env:
  MAKEOPTS: -j2

jobs:
  mpy_cross:
    name: mpy-cross
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN2 }}
    - name: Build mpy-cross
      run: make $MAKEOPTS -C micropython/mpy-cross
    - name: Upload mpy-cross
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: pybricks-mpy-cross
        path: micropython/mpy-cross/pybricks-mpy-cross

  unix_coverage:
    name: unix coverage
    needs: mpy_cross
    runs-on: ubuntu-latest
    env:
      PYBRICKS_NO_REDIRECT_STDOUT: 1
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN2 }}
    - name: Download mpy-cross
      uses: actions/download-artifact@v1
      with:
        name: pybricks-mpy-cross
        path: micropython/mpy-cross
    - name: Fix file permission
      run: chmod +x micropython/mpy-cross/pybricks-mpy-cross
    - name: Build
      run: |
        cd micropython
        git submodule update --init --depth=1 lib/axtls
        git submodule update --init --depth=1 lib/berkeley-db-1.xx
        git submodule update --init --depth=1 lib/libffi
        make $MAKEOPTS -C ports/unix deplibs
        make $MAKEOPTS -C ports/unix coverage
    - name: Test
      if: success()
      run: |
        cd micropython
        (cd tests && MICROPY_CPYTHON3=python3 MICROPY_MICROPYTHON=../ports/unix/micropython_coverage ./run-tests)
        (cd tests && MICROPY_CPYTHON3=python3 MICROPY_MICROPYTHON=../ports/unix/micropython_coverage ./run-tests -d thread)
        (cd tests && MICROPY_CPYTHON3=python3 MICROPY_MICROPYTHON=../ports/unix/micropython_coverage ./run-tests --emit native)
        (cd tests && MICROPY_CPYTHON3=python3 MICROPY_MICROPYTHON=../ports/unix/micropython_coverage ./run-tests --via-mpy -d basics float)
        # test when input script comes from stdin
        cat tests/basics/0prelim.py | ports/unix/micropython_coverage | grep -q 'abc'
    - name: List failed tests
      if: failure()
      run: (cd micropython/tests && for exp in *.exp; do testbase=$(basename $exp .exp); echo -e "\nFAILURE $testbase"; diff -u $testbase.exp $testbase.out; done)

  ev3dev_stretch:
    name: ev3dev-stretch
    needs: mpy_cross
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Install QEMU
      run: |
        sudo apt-get update
        sudo apt-get install qemu-user-static
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN2 }}
    - name: Download mpy-cross
      uses: actions/download-artifact@v1
      with:
        name: pybricks-mpy-cross
        path: micropython/mpy-cross
    - name: Fix file permission
      run: chmod +x micropython/mpy-cross/pybricks-mpy-cross
    - name: Create docker container
      run: bricks/ev3dev/docker/setup.sh armel
    - name: Build
      run: docker exec --tty pybricks-ev3dev_armel make
    - name: Test
      if: success()
      run: |
        docker exec --tty pybricks-ev3dev_armel make test
        docker exec --tty pybricks-ev3dev_armel make test-ev3dev
    - name: List failed tests
      if: failure()
      run: tests/dump-out-files.sh
    - name: Upload pybricks-micropython
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: pybricks-micropython
        path: bricks/ev3dev/pybricks-micropython

  ev3dev_bionic:
    name: ev3dev-bionic
    needs: mpy_cross
    runs-on: ubuntu-latest
    env:
      CROSS_COMPILE: ""
    steps:
    - name: Install rerequisites
      run: |
        sudo apt-add-repository --update --yes ppa:ev3dev/tools
        sudo apt-get install --no-install-recommends --yes \
        alsa-utils \
        espeak \
        ev3dev-media \
        ev3dev-mocks \
        libasound2-plugin-ev3dev \
        libffi-dev \
        libgrx-3.0-dev \
        libi2c-dev \
        libmagickwand-6.q16-3 \
        libudev-dev \
        libumockdev0 \
        pkg-config \
        uthash-dev \
        xfonts-100dpi
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN2 }}
    - name: Download mpy-cross
      uses: actions/download-artifact@v1
      with:
        name: pybricks-mpy-cross
        path: micropython/mpy-cross
    - name: Fix file permission
      run: chmod +x micropython/mpy-cross/pybricks-mpy-cross
    - name: Build
      run: make $MAKEOPTS -C bricks/ev3dev
    - name: Test
      if: success()
      run: |
        make $MAKEOPTS -C bricks/ev3dev test
        make $MAKEOPTS -C bricks/ev3dev test-ev3dev
    - name: List failed tests
      if: failure()
      run: tests/dump-out-files.sh

  cross_compiler:
    name: download cross-compiler
    runs-on: ubuntu-latest
    steps:
    - name: Check cache
      id: check-cache
      uses: actions/cache@v1
      with:
        path: ${{ runner.tool_cache }}/gcc-arm
        key: gcc-arm
    - name: Download
      if: steps.check-cache.outputs.cache-hit != 'true'
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '8-2019-q3'
        directory: ${{ runner.tool_cache }}/gcc-arm

  cityhub_firmware:
    name: cityhub firmware
    needs: [cross_compiler, mpy_cross]
    runs-on: ubuntu-latest
    steps:
    - name: Install cross-compiler
      uses: actions/cache@v1
      with:
        path: ${{ runner.tool_cache }}/gcc-arm
        key: gcc-arm
    - name: Add cross-compiler to path
      run: echo ::add-path::${{ runner.tool_cache }}/gcc-arm/bin
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN2 }}
    - name: Download mpy-cross
      uses: actions/download-artifact@v1
      with:
        name: pybricks-mpy-cross
        path: micropython/mpy-cross
    - name: Fix file permission
      run: chmod +x micropython/mpy-cross/pybricks-mpy-cross
    - name: Build
      run: make $MAKEOPTS -C bricks/cityhub
    - name: Upload firmware
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: cityhub-firmware
        path: bricks/cityhub/build/firmware-base.bin
    - name: Upload firmware metadata
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: cityhub-firmware
        path: bricks/cityhub/build/firmware.metadata.json
    - name: Upload main.py
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: cityhub-firmware
        path: bricks/cityhub/main.py

  cplushub_firmware:
    name: cplushub firmware
    needs: [cross_compiler, mpy_cross]
    runs-on: ubuntu-latest
    steps:
    - name: Install cross-compiler
      uses: actions/cache@v1
      with:
        path: ${{ runner.tool_cache }}/gcc-arm
        key: gcc-arm
    - name: Add cross-compiler to path
      run: echo ::add-path::${{ runner.tool_cache }}/gcc-arm/bin
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN2 }}
    - name: Download mpy-cross
      uses: actions/download-artifact@v1
      with:
        name: pybricks-mpy-cross
        path: micropython/mpy-cross
    - name: Fix file permission
      run: chmod +x micropython/mpy-cross/pybricks-mpy-cross
    - name: Build
      run: make $MAKEOPTS -C bricks/cplushub
    - name: Upload firmware
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: cplushub-firmware
        path: bricks/cplushub/build/firmware-base.bin
    - name: Upload firmware metadata
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: cplushub-firmware
        path: bricks/cplushub/build/firmware.metadata.json
    - name: Upload main.py
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: cplushub-firmware
        path: bricks/cplushub/main.py

  movehub_firmware:
    name: movehub firmware
    needs: [cross_compiler, mpy_cross]
    runs-on: ubuntu-latest
    steps:
    - name: Install cross-compiler
      uses: actions/cache@v1
      with:
        path: ${{ runner.tool_cache }}/gcc-arm
        key: gcc-arm
    - name: Add cross-compiler to path
      run: echo ::add-path::${{ runner.tool_cache }}/gcc-arm/bin
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN2 }}
    - name: Download mpy-cross
      uses: actions/download-artifact@v1
      with:
        name: pybricks-mpy-cross
        path: micropython/mpy-cross
    - name: Fix file permission
      run: chmod +x micropython/mpy-cross/pybricks-mpy-cross
    - name: Build
      run: make $MAKEOPTS -C bricks/movehub
    - name: Upload firmware
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: movehub-firmware
        path: bricks/movehub/build/firmware-base.bin
    - name: Upload firmware metadata
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: movehub-firmware
        path: bricks/movehub/build/firmware.metadata.json
    - name: Upload main.py
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: movehub-firmware
        path: bricks/movehub/main.py

  primehub_firmware:
    name: primehub firmware
    needs: [cross_compiler, mpy_cross]
    runs-on: ubuntu-latest
    steps:
    - name: Install cross-compiler
      uses: actions/cache@v1
      with:
        path: ${{ runner.tool_cache }}/gcc-arm
        key: gcc-arm
    - name: Add cross-compiler to path
      run: echo ::add-path::${{ runner.tool_cache }}/gcc-arm/bin
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN2 }}
    - name: Download mpy-cross
      uses: actions/download-artifact@v1
      with:
        name: pybricks-mpy-cross
        path: micropython/mpy-cross
    - name: Fix file permission
      run: chmod +x micropython/mpy-cross/pybricks-mpy-cross
    - name: Build
      run: make $MAKEOPTS -C bricks/primehub
    - name: Upload firmware
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: primehub-firmware
        path: bricks/primehub/build/firmware-base.bin
    - name: Upload firmware metadata
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: primehub-firmware
        path: bricks/primehub/build/firmware.metadata.json
    - name: Upload main.py
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: primehub-firmware
        path: bricks/primehub/main.py

  nxt_firmware:
    name: nxt firmware
    needs: [cross_compiler, mpy_cross]
    runs-on: ubuntu-latest
    steps:
    - name: Install cross-compiler
      uses: actions/cache@v1
      with:
        path: ${{ runner.tool_cache }}/gcc-arm
        key: gcc-arm
    - name: Add cross-compiler to path
      run: echo ::add-path::${{ runner.tool_cache }}/gcc-arm/bin
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN2 }}
    - name: Fix submodule credetials
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN2 }}
      run: |
        git config submodule.bricks/nxt/nxt-firmware-drivers.url https://${GITHUB_TOKEN}@github.com/pybricks/nxt-firmware-drivers.git
    - name: Download mpy-cross
      uses: actions/download-artifact@v1
      with:
        name: pybricks-mpy-cross
        path: micropython/mpy-cross
    - name: Fix file permission
      run: chmod +x micropython/mpy-cross/pybricks-mpy-cross
    - name: Build
      run:  make $MAKEOPTS -C bricks/nxt
    - name: Upload firmware
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: nxt-firmware
        path: bricks/nxt/build/firmware.bin

  debug:
    name: debug firmware
    needs: [cross_compiler, mpy_cross]
    runs-on: ubuntu-latest
    steps:
    - name: Install cross-compiler
      uses: actions/cache@v1
      with:
        path: ${{ runner.tool_cache }}/gcc-arm
        key: gcc-arm
    - name: Add cross-compiler to path
      run: echo ::add-path::${{ runner.tool_cache }}/gcc-arm/bin
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN2 }}
    - name: Download mpy-cross
      uses: actions/download-artifact@v1
      with:
        name: pybricks-mpy-cross
        path: micropython/mpy-cross
    - name: Fix file permission
      run: chmod +x micropython/mpy-cross/pybricks-mpy-cross
    - name: Build
      run: make $MAKEOPTS -C bricks/debug build/firmware.dfu

  pbio:
    name: pbio tests
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install --yes doxygen
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN2 }}
    - name: Build
      run: |
        make $MAKEOPTS -C lib/pbio/test
        ./lib/pbio/test/build/test-pbio
    - name: Build docs
      run: |
        make $MAKEOPTS -C lib/pbio/doc
    - name: Build coverage
      run: |
        make $MAKEOPTS -C lib/pbio/test COVERAGE=1
        ./lib/pbio/test/build-coverage/test-pbio
