name: Format

# TODO: only do this on pull requests and add commit if there is a diff
on: [push, pull_request]

jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
    - name: Install uncrustify
      run: |
        sudo apt-add-repository --update --yes ppa:pybricks/ppa
        sudo apt-get install uncrustify
        uncrustify --version
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install black
      run:  python -m pip install black
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        path: tmp
    - name: Get tag
      id: get_tag
      run: echo ::set-output name=micropython_tag::$(cat tmp/micropython-tag)
    - name: Checkout MicroPython
      uses: actions/checkout@v2
      with:
        repository: pybricks/micropython
        ref: ${{ steps.get_tag.outputs.micropython_tag }}
        path: micropython
        token: ${{ secrets.GITHUB_TOKEN2 }}
    - name: Checkout Pybricks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN2 }}
      run: |
        cd micropython
        git config submodule.ports/pybricks.url https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git submodule update --init --no-fetch ports/pybricks
        cd ports/pybricks
        git fetch --depth=1 origin $GITHUB_SHA
        git checkout FETCH_HEAD
    - name: Run codeformat.py
      run: |
        cd micropython/ports/pybricks
        ./tools/codeformat.py
        git diff --exit-code
