name: Format

# TODO: only do this on pull requests and add commit if there is a diff
on: [push, pull_request]

jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
    - name: Install uncrustify
      run: |
        sudo apt-add-repository --update --yes ppa:pybricks/ppa
        sudo apt-get install uncrustify
        uncrustify --version
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install black
      run:  python -m pip install black
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN2 }}
    - name: Run codeformat.py
      run: |
        ./tools/codeformat.py
        git diff --exit-code
